export default {
  index: {
    title: '전체 글',
    theme: {
      layout: 'raw',
      breadcrumb: false,
      sidebar: false,
      toc: false,
      pagination: false
    }
  },
  'ai-native-engineer-agent-orchestration': 'AI-Native Engineer 시대: 에이전트 오케스트레이션이 새로운 핵심 역량이 되다',
  'curl-special-characters-tips': 'curl에서 특수문자 때문에 삽질한 적 있다면 — !, @, $ 완벽 정복 가이드',
  'ai-team-building-claude-code': '1인 개발자의 AI 팀 빌딩 — Claude Code로 멀티 에이전트 팀을 설계하는 법',
  'skills-as-a-saas-orchestration': 'Skills as a SaaS: 스킬 하나가 서비스가 되기까지',
  'system-separation-moves-complexity': '시스템 분리는 복잡성을 줄이는 게 아니라 옮기는 것이다',
  'reading-vs-understanding-api-docs': 'API 문서를 읽는 것과 API를 이해하는 것은 다르다',
  'claude-code-2-1-59-update': 'Claude Code 2.1.59 업데이트: 드디어 \'기억(Memory)\'을 탑재하다',
  'llm-harness-driven-agent': 'LLM 벤치마크는 왜 현실 코딩에서 무너지는가: Harness 주도 에이전트 설계',
  'claude-code-ban-risk-gemini-exchange': 'Claude Code 자동화의 함정: 계정 밴 리스크와 Gemini 3.1 Pro 두뇌 이식기',
  'openclaw-100days-real-experience': 'OpenClaw 100일 실전기 — "초보자에엔 어렵다"는 리뷰가 놓친 것',
  'cloud-blog-skill-reference': 'Cloud Blog Skill 분석 — Claude Code 블로그 자동화의 끝판왕?',
  'skill-engineering-real-practice': 'AI 에이전트 스킬 엔지니어링 — 이론은 됐고, 실전에서 뭐가 달라지는지 보여준다',
  'claudemd-delete-paper-webmcp': '"CLAUDE.md 지워라" 논문의 진짜 의미 — AI 에이전트 컨텍스트의 미래',
  'coda-ai-documentation-framework': 'CODA — AI 코딩 에이전트를 위한 문서화 프레임워크',
  'ai-bot-collaboration': 'AI 봇 2마리가 협업하는 법 — OpenClaw 멀티 에이전트 실전기',
  'ai-showcase-7demos-one-app': 'Next.js 하나로 7개 데모 사이트 만들기 — AI 외주 쇼케이스 구축기',
  'vercel-telegram-realtime-chat': 'Vercel + Telegram 실시간 채팅 위젯 — DB 없이, 서버 없이',
  'sonnet46-opus-killer-budget': 'Sonnet 4.6 — Opus의 1/5 가격인데, 70%가 더 좋다고?',
  'agent-skills-ecosystem': 'AI 코딩 에이전트의 npm — Agent Skills 생태계 완전 정복',
  'gemini-3-vs-31-pro-real-code-review': 'Gemini 3 Pro vs 3.1 Pro: 실제 코드 11만 자를 던져봤다',
  'opus-surrounded': 'Opus가 포위됐다 — Sonnet 4.6과 Gemini 3.1 Pro, 48시간의 협공',
  'gemini-cli-google-mcp-handson': 'Gemini CLI + Google MCP로 풀스택 앱 클라우드 배포하기',
  'blog-seo-basics-to-practice': '블로그 SEO, 기본 개념부터 실전 셋팅까지',
  'building-multi-agent-system-part1': '로컬에서 AI 멀티 에이전트 만들기 (1) — 설계와 환경 구성',
  'building-multi-agent-system-part2': '로컬에서 AI 멀티 에이전트 만들기 (2) — 통신, 모니터링, 그리고 실험',
}
